# Generated by Django 3.2 on 2022-03-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciaccident',
            fields=[
                ('cahseq', models.IntegerField(primary_key=True, serialize=False)),
                ('cahdate', models.CharField(blank=True, max_length=10, null=True)),
                ('cahcontent', models.CharField(blank=True, max_length=1000, null=True)),
                ('cahaction', models.CharField(blank=True, max_length=1000, null=True)),
                ('cahcode', models.CharField(blank=True, max_length=10, null=True)),
                ('cicode', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ciaccident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ciall',
            fields=[
                ('ciseq', models.IntegerField(primary_key=True, serialize=False)),
                ('cicode', models.CharField(max_length=20)),
                ('ciname', models.CharField(blank=True, max_length=255, null=True)),
                ('cimingong', models.CharField(blank=True, max_length=10, null=True)),
                ('ciinout', models.CharField(blank=True, max_length=10, null=True)),
                ('ciplacecode', models.CharField(blank=True, max_length=10, null=True)),
                ('ciduty', models.CharField(blank=True, max_length=10, null=True)),
                ('ciopercode', models.CharField(blank=True, max_length=10, null=True)),
                ('ciaddr', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('ctmnotidate', models.CharField(blank=True, max_length=10, null=True)),
                ('ctmreviewat', models.CharField(blank=True, max_length=5, null=True)),
                ('cifloorcode', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'ciall',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='cicahcause',
            fields=[
                ('cahcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cahcodename', models.CharField(db_column='cahcodeName', max_length=20)),
            ],
            options={
                'db_table': 'cicahcause',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='cifloorinfo',
            fields=[
                ('cifloorcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('flocodename', models.CharField(db_column='flocodeName', max_length=10)),
            ],
            options={
                'db_table': 'cifloorinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ciinst',
            fields=[
                ('caseq', models.IntegerField(primary_key=True, serialize=False)),
                ('ciseq', models.IntegerField(blank=True, null=True)),
                ('cainstno', models.CharField(blank=True, max_length=10, null=True)),
                ('cacuser', models.CharField(blank=True, max_length=20, null=True)),
                ('cacdate', models.CharField(blank=True, max_length=10, null=True)),
                ('ciinstcode', models.CharField(blank=True, max_length=10, null=True)),
                ('ciinst', models.CharField(blank=True, max_length=30, null=True)),
                ('cainstcode', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ciinst',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='cimanager',
            fields=[
                ('csseq', models.IntegerField(primary_key=True, serialize=False)),
                ('ciseq', models.IntegerField(blank=True, null=True)),
                ('ciindgroup', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'cimanager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='cioperation',
            fields=[
                ('ciopercode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('opcodename', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'cioperation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ciplaceinfo',
            fields=[
                ('ciplacecode', models.CharField(blank=True, max_length=10, null=True)),
                ('plcodename', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ciplaceinfo',
                'managed': False,
            },
        ),
    ]
